### ISSUE TITLE
If I jump into a portal from high up I don't keep my velocity.

### ISSUE THREAD

**Issue by FireFlix-Games** [Adrodoc55/ApertureCraftVanilla#22] opened 2020-04-27 22:38 UTC
If I jump into a portal from high up I don't keep my velocity.

**Comment by sillydomnom** [comment] 2020-04-28 05:01
See #5 for this issue

**Comment by Adrodoc** [comment] 2020-04-28 07:09
Duplicate of #5

**Closed as completed by Adrodoc** 2020-04-28 07:09 UTC
Labels: duplicate
