### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by Ijdtm7** [Adrodoc55/ApertureCraftVanilla#23] opened 2020-04-28 14:40 UTC
Hey there, Adrodoc, I saw the 1.15 branch and am wondering if you are now working on updating the portal system?

**Comment by Adrodoc** [comment] 2020-04-28 15:42
Duplicate of #20
TLDR: I am currently not working on this project, but I may come back to this in the future.

**Closed as completed by Adrodoc** 2020-04-28 15:42 UTC
Labels: duplicate, question
